name: Download Files with gdown

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:

jobs:
  download_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gdown and download files
      run: |
        LIST_FILE="https://raw.githubusercontent.com/Bogyi2024/log/main/links.txt"
        while IFS= read -r url; do
          url=$(echo "$url" | xargs)
          gdown "$url"
        done < "$LIST_FILE"
